#!/bin/sh

. /lib/functions.sh

if [ "${ACTION}" = "released" ]; then
	/usr/bin/button_released &
elif [ "${ACTION}" = "pressed" ]; then
	/usr/bin/button_pressed &
fi


#if [ "$SEEN" -lt 2 ]
#then
#	/usr/bin/wifionoff
#elif [ "$SEEN" -gt 5 ]
#then
#	echo "FACTORY RESET" > /dev/console
#	/usr/bin/flashleds &
#	jffs2reset -y && reboot &
#fi
