#!/bin/sh /etc/rc.common
# Copyright (C) 2006-2011 OpenWrt.org

START=50
STOP=50

USE_PROCD=1

lan_ip=$(uci get network.lan.ipaddr)

start_service() {
	while [ -z "$(ifconfig wlan0)" ]; do
		sleep 5
	done
	password=`tor --hash-password ''|tail -n1`
	sed -i "s/^HashedControlPassword.*/HashedControlPassword $password/g" /etc/tor/torrc
	sed -i "s/192.168\..*\..*:/$lan_ip:/g" /etc/tor/torrc
	[ -f /var/run/tor.pid ] || {
		touch /var/run/tor.pid
		chown tor:tor /var/run/tor.pid
	}
	[ -d /var/lib/tor ] || {
		mkdir -m 0755 -p /var/lib/tor
		chmod 0700 /var/lib/tor
		chown tor:tor /var/lib/tor
	}
	[ -d /var/log/tor ] || {
		mkdir -m 0755 -p /var/log/tor
		chown tor:tor /var/log/tor
	}
	procd_open_instance
	procd_set_param command /usr/sbin/tor --runasdaemon 0
	procd_close_instance
}
